blank_issues_enabled: false
contact_links:
  - name: Discord Support Server
    url: https://discord.gg/qmnDsSD
    about: If you have any questions, please join our Discord server instead of creating an issue.